# Generated by Django 2.2.1 on 2020-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ISBN',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
