# Generated by Django 2.2.1 on 2020-12-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_book',
            name='movie',
            field=models.CharField(max_length=100),
        ),
    ]
