# Generated by Django 2.2.1 on 2020-12-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201201_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_book',
            old_name='movie',
            new_name='book',
        ),
    ]
